### ISSUE TITLE
Release 2.0 follow-up

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#378]
**Release:** December 2022

Current (more or less stable) state can be found in [TEXTEXT_2_0_Dev](https://github.com/textext/textext/tree/TEXTEXT_2_0_Dev) branch, more recent developments in my fork [TEXTEXT_2_0](https://github.com/jcwinkler/textext/tree/TEXTEXT_2_0) (without any guarantee). Do not use that stuff in a productive environment.

The following list reflects the state of my local development which from time to time flows into the above mentioned branches.

### Main goals:
- Support installation via Inkscape’s extension manager
- Limit compatibility to Inkscape 1.2.x (inkex API >= 1.2.0)
- Remove Python 2.x compatibility
- Ensure Python >= 3.6 compatibility 
- General code clean up
- consistent code style

### General tasks

**Code**
- [x] Simplify/ clean-up requirements.py (we need not the complexity of the old days with pstoedit/pdf2svg etc)
- [x] Clean-up workflow in base.py (use meta data structures instead of tons of variables, etc.)
- [x] Simplify/ clean-up setup.py
- [x] Clean-up logging
- [x] Re-think what is in which module: environment – dependencies – logging
- [ ] Refactor gui code
  - [ ] more meaningful names (#161)
  - [ ] alignment icons for dark theme (#237)
  - [ ] simplify save/preview callback mechanism
- [ ] winapp_paths.py not needed for TexText (but for setup.py)

**Functionality**
- [ ] User must be able to manually define location of latex interpreters (because extension manager cannot do this)
	- [x] Create a configure dialog
	- [ ] Include this dialog into gui
- [ ] Easy way to edit preamble
- [ ] Meaningful error messages of unexpected errors (traceback)
- [ ] Add possibility to import snippet from file
- [ ] Setup via MS Store

**Check**
- [ ] Handling of preamble
- [x] No Python 2.x code anymore

**Fix known bugs**
- [ ] Strokes are not colored after re-editing node
- [ ] Images in pdf code not included (#358)

**Doc**
- [ ] User: Add known issue section
- [ ] Code: consequent rst sphinx style
- [ ] Add #153

**Pass PyLint requirements**
- [x] setup.py
- [ ] base.py
- [x] environment.py
- [x] errors.py
- [ ] gui.py
- [x] log_util.py
- [x] settings.py
- [x] utility.py

**Tests/CI**
- [ ] Check
- [ ] Remove Inkscape 1.0.1 tests
- [ ] Add linting (#377)
- [ ] sign releases (#231)

**Comment by jcwinkler** [comment]
Here some snapshots of the new TexText window:

![grafik](https://github.com/textext/textext/assets/11866252/0944dfaf-e206-4f6b-b0cf-c406d2d582ed)

![grafik](https://github.com/textext/textext/assets/11866252/5e390910-8783-40bf-acb8-769b809a5013)
